Import des données

In [4]:
import pandas as pd
df = pd.read_csv(
'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)

df.head(2)

/tmp/ipykernel_8213/531837865.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2

Imports utiles pour le DM

### Question 1

On doit mettre à jour la variable code_commune en utilisant la variable actuelle et la variable code_departement. Pour cela, on va devoir concaténer les deux variables de telle sorte à obtenir ensuite un code à 5 chiffres. Les deux premiers chiffres correspondront au département (par exemple : 01 pour l'Ain, 59 pour le Nord) et les trois derniers au code commune (par exemple : 049 pour le code commune 49 dans le cas de Montrouge).

Pour cela, nous allons utiliser la fonction code_commune_complet que nous importons depuis fonctions.py qui va nous permettre de rajouter des zéros devant le code commune de façon à avoir un code commune de 3 chiffres.

In [3]:
df[df['libelle_commune'] == "Montrouge"]

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
34535,92,Hauts-de-Seine,49,Montrouge,Nathalie,ARTHAUD,96
69780,92,Hauts-de-Seine,49,Montrouge,Fabien,ROUSSEL,499
105025,92,Hauts-de-Seine,49,Montrouge,Emmanuel,MACRON,8291
140270,92,Hauts-de-Seine,49,Montrouge,Jean,LASSALLE,349
175515,92,Hauts-de-Seine,49,Montrouge,Marine,LE PEN,1775
210760,92,Hauts-de-Seine,49,Montrouge,Éric,ZEMMOUR,1466
246005,92,Hauts-de-Seine,49,Montrouge,Jean-Luc,MÉLENCHON,6683
281250,92,Hauts-de-Seine,49,Montrouge,Anne,HIDALGO,508
316495,92,Hauts-de-Seine,49,Montrouge,Yannick,JADOT,1952
351740,92,Hauts-de-Seine,49,Montrouge,Valérie,PÉCRESSE,1468
386985,92,Hauts-de-Seine,49,Montrouge,Philippe,POUTOU,141
422230,92,Hauts-de-Seine,49,Montrouge,Nicolas,DUPONT-AIGNAN,311
457475,92,Hauts-de-Seine,49,Montrouge,NaN,abstentions,5162
492720,92,Hauts-de-Seine,49,Montrouge,NaN,blancs,283
527965,92,Hauts-de-Seine,49,Montrouge,NaN,nuls,117