Import des données

In [14]:
import pandas as pd
df = pd.read_csv(
'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)

df.head(2)

/tmp/ipykernel_8213/531837865.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2

Imports utiles pour le DM

### Question 1

On doit mettre à jour la variable code_commune en utilisant la variable actuelle et la variable code_departement. Pour cela, on va devoir concaténer les deux variables de telle sorte à obtenir ensuite un code à 5 chiffres. Les deux premiers chiffres correspondront au département (par exemple : 01 pour l'Ain, 59 pour le Nord) et les trois derniers au code commune (par exemple : 049 pour le code commune 49 dans le cas de Montrouge).

In [15]:
df['code_commune'] = df['code_commune'].astype(str).str.zfill(3)

df['code_commune'] = df['code_departement'].astype(str) + df['code_commune']

df.head(20)

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,01001,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,01002,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,01004,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,01005,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,01006,Ambléon,Nathalie,ARTHAUD,0
5,01,Ain,01007,Ambronay,Nathalie,ARTHAUD,10
6,01,Ain,01008,Ambutrix,Nathalie,ARTHAUD,2
7,01,Ain,01009,Andert-et-Condon,Nathalie,ARTHAUD,1
8,01,Ain,01010,Anglefort,Nathalie,ARTHAUD,5
9,01,Ain,01011,Apremont,Nathalie,ARTHAUD,0
10,01,Ain,01012,Aranc,Nathalie,ARTHAUD,4
11,01,Ain,01013,Arandas,Nathalie,ARTHAUD,1
12,01,Ain,01014,Arbent,Nathalie,ARTHAUD,7
13,01,Ain,01015,Arboys en Bugey,Nathalie,ARTHAUD,0
14,01,Ain,01016,Arbigny,Nathalie,ARTHAUD,1
15,01,Ain,01017,Argis,Nathalie,ARTHAUD,1
16,01,Ain,01019,Armix,Nathalie,ARTHAUD,0
17,01,Ain,01021,Ars-sur-Formans,Nathalie,ARTHAUD,2
18,01,Ain,01022,Artemare,Nathalie,ARTHAUD,7
19,01,Ain,01023,Asnières-sur-Saône,Nathalie,ARTHAUD,0

Nous devons également créer une colonne candidat qui comporte les prénoms et les noms de tous les candidats. Pour cela, nous allons concaténer les colonnes prenom et nom.

In [24]:
df["candidat"] = df["prenom"].astype(str) + " " + df["nom"].astype(str)

print(df['candidat'].unique())

['Nathalie ARTHAUD' 'Fabien ROUSSEL' 'Emmanuel MACRON' 'Jean LASSALLE'
 'Marine LE PEN' 'Éric ZEMMOUR' 'Jean-Luc MÉLENCHON' 'Anne HIDALGO'
 'Yannick JADOT' 'Valérie PÉCRESSE' 'Philippe POUTOU'
 'Nicolas DUPONT-AIGNAN' 'nan abstentions' 'nan blancs' 'nan nuls']

### Question 2

On souhaite déterminer le nombre de candidats qu'il y avait aux élections présidentielles de 2022. Pour cela, on va compter le nombre de candidats différents en excluant les votes blancs, les votes nuls et l'abstention.

In [31]:
candidats = len(df[~df.isin(['nan abstentions', 'nan blancs', 'nan nuls'])]['candidat'].unique())

f"En 2022, il y avait {candidats} candidats à l'élection présidentielle."

"En 2022, il y avait 13 candidats à l'élection présidentielle."